//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int Id { get; set; }
        public Nullable<int> Vehiculo { get; set; }
        public Nullable<int> Cliente { get; set; }
        public string Ralladuras { get; set; }
        public string CantidadCombustible { get; set; }
        public string GomaRepuesto { get; set; }
        public string Gato { get; set; }
        public string RoturaCristal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Empleado { get; set; }
        public string EstadoGomasDelanteras { get; set; }
        public string EstadoGomasTraseras { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
