//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaRentCarEntities : DbContext
    {
        public SistemaRentCarEntities()
            : base("name=SistemaRentCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Inspeccion> Inspeccions { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Modelo> Modeloes { get; set; }
        public virtual DbSet<RentaDevolucion> RentaDevolucions { get; set; }
        public virtual DbSet<TipoCombustible> TipoCombustibles { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculoes { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
    
        public virtual int updateVehiculoStatus(Nullable<int> vehiculo, Nullable<System.DateTime> fecha)
        {
            var vehiculoParameter = vehiculo.HasValue ?
                new ObjectParameter("vehiculo", vehiculo) :
                new ObjectParameter("vehiculo", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateVehiculoStatus", vehiculoParameter, fechaParameter);
        }
    }
}
