//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentaDevolucion
    {
        public int Id { get; set; }
        public Nullable<int> Empleado { get; set; }
        public Nullable<int> Vehiculo { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<System.DateTime> FechaRenta { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<decimal> MontoDia { get; set; }
        public Nullable<int> Dias { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
