//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Inspeccions = new HashSet<Inspeccion>();
            this.RentaDevolucions = new HashSet<RentaDevolucion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Chasis { get; set; }
        public string Motor { get; set; }
        public string Placa { get; set; }
        public string Estado { get; set; }
        public int TipoVehiculo { get; set; }
        public int Marca { get; set; }
        public int Modelo { get; set; }
        public int TipoCombustible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccion> Inspeccions { get; set; }
        public virtual Marca Marca1 { get; set; }
        public virtual Modelo Modelo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentaDevolucion> RentaDevolucions { get; set; }
        public virtual TipoCombustible TipoCombustible1 { get; set; }
        public virtual TipoVehiculo TipoVehiculo1 { get; set; }
    }
}
